test with broken version of semgrep

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -82,26 +82,16 @@ jobs:
       #   run: echo '1 == 1' | semgrep -l python -e '$X == $X' -
       # - name: e2e spacegrep test
       #   run: echo '1 == 1' | semgrep -l generic -e '$X == $X' -
-      - name: test linked libraries
+      - name: install package
+        run: pip3 install semgrep==1.5.1
+      - name: test package
         run: |
-          echo "/usr/bin/foo"
-          if ! echo /usr/bin/foo | grep -qv /Users/; then
-            echo "Error: foo"
+          otool -L /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/semgrep/bin/semgrep-core | grep /Users/
+
+          if ! otool -L /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/semgrep/bin/semgrep-core | grep -qv /Users/; then
+            echo "Error: semgrep-core has been linked with a user-specific libary which will not be available on other machines."
             exit 1
           fi
-
-          echo "/Users/ssm-user"
-          if ! echo /Users/ssm-user | grep -qv /Users/; then
-            echo "Error: users"
-            exit 1
-          fi
-
-          echo "Done"
-
-          # if otool -L /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/semgrep/bin/semgrep-core | grep -qv /Users/; then
-          #   echo "Error: semgrep-core has been linked with a user-specific libary which will not be available on other machines."
-          #   exit 1
-          # fi
 
   # test-macos-release:
   #   name: test macOS release
