test negated error codes

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -85,14 +85,14 @@ jobs:
       - name: test linked libraries
         run: |
           echo "/usr/bin/foo"
-          if echo /usr/bin/foo | grep -qv /Users/; then
-            echo "Error: semgrep-core has been linked with a user-specific libary which will not be available on other machines."
+          if ! echo /usr/bin/foo | grep -qv /Users/; then
+            echo "Error: foo"
             exit 1
           fi
 
           echo "/Users/ssm-user"
-          if echo /Users/ssm-user | grep -qv /Users/; then
-            echo "Error: semgrep-core has been linked with a user-specific libary which will not be available on other machines."
+          if ! echo /Users/ssm-user | grep -qv /Users/; then
+            echo "Error: users"
             exit 1
           fi
 
@@ -102,7 +102,6 @@ jobs:
           #   echo "Error: semgrep-core has been linked with a user-specific libary which will not be available on other machines."
           #   exit 1
           # fi
-
 
   # test-macos-release:
   #   name: test macOS release
